name: Linting & formatting

on:
  push:
    branches: ['master', 'actions']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint it
        run: pnpm run lint:no-fmt
